encrypted_dir := "target/.encrypted.disk"
decrypted_dir := "target/decrypted.disk"

default: build

build:
    cargo build

mount: build
    mkdir -p {{decrypted_dir}}
    cargo run -- --encrypted-dir {{encrypted_dir}} --decrypted-dir {{decrypted_dir}}

umount:
    umount {{decrypted_dir}} || diskutil unmount {{decrypted_dir}}

run: build
    cargo run -- --encrypted-dir {{encrypted_dir}} --decrypted-dir {{decrypted_dir}}

test:
    cargo test

release:
    cargo build --release

clean:
    cargo clean
    rm -rf {{encrypted_dir}} {{decrypted_dir}}
