// Copyright 2026 Alexander Orlov <alexander.orlov@loxal.net>

//! Integration tests + builder for the committed example fixture.
//!
//! Design decisions:
//! - The committed `examples/example_export.json` is a small, hand-curated
//!   synthetic fixture (~22 items) generated by [`build_curated_fixture`].
//!   It is NOT a redacted snapshot of a real vault — every field is
//!   fabricated. Nothing in it originates from a real Bitwarden export.
//! - To regenerate the file: `just regenerate-example` (or the raw
//!   `cargo test regenerate_example_fixture -- --ignored` command).
//! - [`example_fixture_matches_generator`] fails loudly if the on-disk
//!   file ever drifts from what the builder produces, which keeps the
//!   committed file auditable.
//! - [`example_fixture_no_leaked_strings`] enforces that every string in
//!   the committed file matches an allowlist — if a future edit
//!   accidentally introduces a string that looks like a real domain or
//!   credential, the test fails.
//! - [`example_fixture_counts_match_readme`] locks in the exact dedup
//!   counts documented in the README.

use std::path::{Path, PathBuf};

use bitwarden_dedup::dedup_items;
use serde_json::{Value, json};

/// The committed synthetic fixture's filename. Uses the
/// `bitwarden_export_<timestamp>.json` shape that real Bitwarden exports
/// use, so the dedup tool is exercised against the same filename pattern
/// its users will throw at it. The `<timestamp>` component is fixed at
/// fixture-creation time and only changes when the fixture is regenerated
/// (rare — see `just regenerate-example`). The `examples/` directory is
/// guarded by `examples_directory_contains_only_fixture` to prevent any
/// other file from being committed alongside.
const FIXTURE_FILENAME: &str = "bitwarden_export_20260411172632.json";

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("examples")
        .join(FIXTURE_FILENAME)
}

/// Build the committed fixture from scratch. Every string here is synthetic.
/// The fixture covers: a unique login, an exact duplicate pair, a URI
/// divergent pair (merges one URI), an Android URI pair (merges one URI),
/// a match-mode divergent pair (merges one URI), a triple duplicate (no
/// URI merge), a same-name-but-different-password pair (NOT merged), a
/// TOTP-bearing login, a reprompt-gated login (skipped), an empty-password
/// login (skipped), an already-tagged [duplicate] login (skipped), a
/// soft-deleted login (skipped), a card (skipped non-login), an identity
/// (skipped non-login), and a secure note (skipped non-login).
fn build_curated_fixture() -> Value {
    const FOLDER_ID: &str = "00000000-0000-0000-0001-000000000001";

    let mut id_counter: u64 = 0;
    let mut next_id = || {
        id_counter += 1;
        format!("00000000-0000-0000-0000-{:012x}", id_counter)
    };

    let login = |id: String,
                 name: &str,
                 user: &str,
                 password: &str,
                 revision: &str,
                 uris: Vec<Value>|
     -> Value {
        json!({
            "id": id,
            "organizationId": null,
            "folderId": FOLDER_ID,
            "type": 1,
            "reprompt": 0,
            "favorite": false,
            "name": name,
            "notes": null,
            "creationDate": "2025-01-01T00:00:00Z",
            "revisionDate": revision,
            "deletedDate": null,
            "collectionIds": null,
            "fields": null,
            "passwordHistory": null,
            "login": {
                "username": user,
                "password": password,
                "totp": null,
                "uris": uris,
                "fido2Credentials": []
            }
        })
    };

    let uri = |u: &str| json!({"uri": u, "match": null});
    let uri_match = |u: &str, m: i64| json!({"uri": u, "match": m});

    let mut items: Vec<Value> = Vec::new();

    // 1. A unique login with no duplicates anywhere in the fixture.
    items.push(login(
        next_id(),
        "Lonely Login",
        "user01@example.test",
        "redacted-password-01",
        "2026-01-01T00:00:00Z",
        vec![uri("https://service01.example.test")],
    ));

    // 2-3. Exact duplicate pair. Newer revision wins, older is dropped, no
    //      URI merge (both have the same URI).
    items.push(login(
        next_id(),
        "Exact Duplicate",
        "user02@example.test",
        "redacted-password-02",
        "2025-06-01T00:00:00Z",
        vec![uri("https://service02.example.test")],
    ));
    items.push(login(
        next_id(),
        "Exact Duplicate",
        "user02@example.test",
        "redacted-password-02",
        "2026-06-01T00:00:00Z",
        vec![uri("https://service02.example.test")],
    ));

    // 4-5. URI-divergent pair. Older has two URIs; newer has one. After
    //      dedup the newer item should absorb the older's second URI.
    items.push(login(
        next_id(),
        "URI Divergent",
        "user03@example.test",
        "redacted-password-03",
        "2025-06-01T00:00:00Z",
        vec![
            uri("https://service03.example.test/primary"),
            uri("https://service03.example.test/secondary"),
        ],
    ));
    items.push(login(
        next_id(),
        "URI Divergent",
        "user03@example.test",
        "redacted-password-03",
        "2026-06-01T00:00:00Z",
        vec![uri("https://service03.example.test/primary")],
    ));

    // 6-7. Android URI pair. Dropped (older) item has an androidapp:// URI
    //      that the kept (newer) item lacks — should be merged in.
    items.push(login(
        next_id(),
        "Mobile App",
        "user04@example.test",
        "redacted-password-04",
        "2025-06-01T00:00:00Z",
        vec![
            uri("https://service04.example.test"),
            uri("androidapp://com.example.service04"),
        ],
    ));
    items.push(login(
        next_id(),
        "Mobile App",
        "user04@example.test",
        "redacted-password-04",
        "2026-06-01T00:00:00Z",
        vec![uri("https://service04.example.test")],
    ));

    // 8-9. Match-mode divergent pair. Same URI string, different match
    //      detection modes. Merger should preserve both records.
    items.push(login(
        next_id(),
        "Match Mode Divergent",
        "user05@example.test",
        "redacted-password-05",
        "2025-06-01T00:00:00Z",
        vec![uri_match("https://service05.example.test", 3)],
    ));
    items.push(login(
        next_id(),
        "Match Mode Divergent",
        "user05@example.test",
        "redacted-password-05",
        "2026-06-01T00:00:00Z",
        vec![uri("https://service05.example.test")],
    ));

    // 10-12. Triple duplicate in one group — exercises the >2-item group
    //        path. All three share URIs so zero URIs are merged.
    for rev in [
        "2024-01-01T00:00:00Z",
        "2025-01-01T00:00:00Z",
        "2026-01-01T00:00:00Z",
    ] {
        items.push(login(
            next_id(),
            "Triple Copy",
            "user06@example.test",
            "redacted-password-06",
            rev,
            vec![uri("https://service06.example.test")],
        ));
    }

    // 13-14. Same name, same username, DIFFERENT password. Must NOT be
    //        merged — proves password is in the dedup key.
    items.push(login(
        next_id(),
        "Two Accounts Same Site",
        "user07@example.test",
        "redacted-password-07a",
        "2026-01-01T00:00:00Z",
        vec![uri("https://service07.example.test")],
    ));
    items.push(login(
        next_id(),
        "Two Accounts Same Site",
        "user07@example.test",
        "redacted-password-07b",
        "2026-01-01T00:00:00Z",
        vec![uri("https://service07.example.test")],
    ));

    // 15. Login with a TOTP seed (unique item). The TOTP placeholder is a
    //     plainly-synthetic string, not an otpauth:// URI, so there's no
    //     chance a human mistakes it for real.
    items.push({
        let mut v = login(
            next_id(),
            "With TOTP",
            "user08@example.test",
            "redacted-password-08",
            "2026-01-01T00:00:00Z",
            vec![uri("https://service08.example.test")],
        );
        v["login"]["totp"] = json!("redacted-totp-seed-08");
        v
    });

    // 16. Reprompt-gated login — must be skipped (too sensitive to auto-merge).
    items.push({
        let mut v = login(
            next_id(),
            "Reprompt Protected",
            "user09@example.test",
            "redacted-password-09",
            "2026-01-01T00:00:00Z",
            vec![uri("https://service09.example.test")],
        );
        v["reprompt"] = json!(1);
        v
    });

    // 17. Empty-password login — must be skipped (would spuriously group on "").
    items.push(login(
        next_id(),
        "No Password Set",
        "user10@example.test",
        "",
        "2026-01-01T00:00:00Z",
        vec![uri("https://service10.example.test")],
    ));

    // 18. Already-tagged [duplicate] login — must be skipped.
    items.push(login(
        next_id(),
        "Already Tagged [duplicate]",
        "user11@example.test",
        "redacted-password-11",
        "2026-01-01T00:00:00Z",
        vec![uri("https://service11.example.test")],
    ));

    // 19. Soft-deleted (in trash) login — must be skipped.
    items.push({
        let mut v = login(
            next_id(),
            "Trashed Item",
            "user12@example.test",
            "redacted-password-12",
            "2026-01-01T00:00:00Z",
            vec![uri("https://service12.example.test")],
        );
        v["deletedDate"] = json!("2026-02-01T00:00:00Z");
        v
    });

    // 20. Card — non-login, passed through.
    items.push(json!({
        "id": next_id(),
        "organizationId": null,
        "folderId": FOLDER_ID,
        "type": 3,
        "reprompt": 0,
        "favorite": false,
        "name": "Example Payment Card",
        "notes": null,
        "creationDate": "2025-01-01T00:00:00Z",
        "revisionDate": "2026-01-01T00:00:00Z",
        "deletedDate": null,
        "collectionIds": null,
        "fields": null,
        "passwordHistory": null,
        "card": {
            "cardholderName": "REDACTED",
            "brand": null,
            "number": null,
            "expMonth": null,
            "expYear": null,
            "code": null
        }
    }));

    // 21. Identity — non-login, passed through.
    items.push(json!({
        "id": next_id(),
        "organizationId": null,
        "folderId": FOLDER_ID,
        "type": 4,
        "reprompt": 0,
        "favorite": false,
        "name": "Example Identity",
        "notes": null,
        "creationDate": "2025-01-01T00:00:00Z",
        "revisionDate": "2026-01-01T00:00:00Z",
        "deletedDate": null,
        "collectionIds": null,
        "fields": null,
        "passwordHistory": null,
        "identity": {
            "title": null,
            "firstName": "REDACTED",
            "middleName": null,
            "lastName": "REDACTED",
            "address1": null,
            "address2": null,
            "address3": null,
            "city": null,
            "state": null,
            "postalCode": null,
            "country": null,
            "company": null,
            "email": null,
            "phone": null,
            "ssn": null,
            "username": null,
            "passportNumber": null,
            "licenseNumber": null
        }
    }));

    // 22. Secure note — non-login, passed through.
    items.push(json!({
        "id": next_id(),
        "organizationId": null,
        "folderId": FOLDER_ID,
        "type": 2,
        "reprompt": 0,
        "favorite": false,
        "name": "Example Secure Note",
        "notes": null,
        "creationDate": "2025-01-01T00:00:00Z",
        "revisionDate": "2026-01-01T00:00:00Z",
        "deletedDate": null,
        "collectionIds": null,
        "fields": null,
        "passwordHistory": null,
        "secureNote": {"type": 0}
    }));

    json!({
        "encrypted": false,
        "folders": [
            {"id": FOLDER_ID, "name": "Folder 01"}
        ],
        "items": items
    })
}

fn load_fixture_items() -> Vec<Value> {
    let path = fixture_path();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    let mut data: Value =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("parsing {}: {e}", path.display()));
    match data.as_object_mut().and_then(|o| o.get_mut("items")) {
        Some(Value::Array(arr)) => std::mem::take(arr),
        _ => panic!("fixture has no 'items' array"),
    }
}

// ---------------------------------------------------------------------------
// Regenerator — run with `just regenerate-example` or
//   cargo test regenerate_example_fixture -- --ignored
// ---------------------------------------------------------------------------

#[test]
#[ignore]
fn regenerate_example_fixture() {
    let fixture = build_curated_fixture();
    let json = serde_json::to_string_pretty(&fixture).expect("serialize fixture");
    std::fs::write(fixture_path(), json + "\n").expect("write fixture");
    eprintln!("wrote {}", fixture_path().display());
}

// ---------------------------------------------------------------------------
// Assertions
// ---------------------------------------------------------------------------

#[test]
fn example_fixture_matches_generator() {
    let on_disk: Value =
        serde_json::from_str(&std::fs::read_to_string(fixture_path()).unwrap()).unwrap();
    let generated = build_curated_fixture();
    assert_eq!(
        on_disk, generated,
        "committed fixture has drifted from build_curated_fixture() in \
         tests/fixture.rs — run `just regenerate-example` to rewrite it"
    );
}

#[test]
fn example_fixture_counts_match_readme() {
    let mut items = load_fixture_items();
    let stats = dedup_items(&mut items);

    assert_eq!(stats.total, 22, "total items in the curated fixture");
    assert_eq!(stats.skipped, 7, "items skipped from dedup");
    assert_eq!(stats.groups, 5, "strict duplicate groups");
    assert_eq!(
        stats.trashed, 6,
        "items routed to Bitwarden Trash by this run"
    );
    assert_eq!(stats.merged, 3, "URIs merged into kept items");
    // Output keeps every input item (losers become trashed, not removed).
    assert_eq!(stats.output, 22);
    assert_eq!(items.len(), 22);
    // Fixture includes one item with `deletedDate` set at the source, so
    // total trashed in the output = 6 (new) + 1 (pre-existing) = 7, and
    // living items = 22 - 7 = 15.
    assert_eq!(
        stats.living, 15,
        "living items = total - already-trashed - newly-trashed"
    );
}

#[test]
fn example_fixture_type_distribution() {
    let items = load_fixture_items();
    let mut counts = [0usize; 5];
    for item in &items {
        if let Some(t) = item.get("type").and_then(Value::as_u64)
            && (t as usize) < counts.len()
        {
            counts[t as usize] += 1;
        }
    }
    assert_eq!(counts[1], 19, "logins in the fixture");
    assert_eq!(counts[2], 1, "secure notes in the fixture");
    assert_eq!(counts[3], 1, "cards in the fixture");
    assert_eq!(counts[4], 1, "identities in the fixture");
}

// ---------------------------------------------------------------------------
// Leak-guard: every string in the committed fixture must match the allowlist.
// Fails loudly if a future edit introduces anything that looks like a real
// credential, domain, or identifier.
// ---------------------------------------------------------------------------

#[test]
fn example_fixture_no_leaked_strings() {
    let on_disk: Value =
        serde_json::from_str(&std::fs::read_to_string(fixture_path()).unwrap()).unwrap();
    let mut path = String::new();
    walk_strings(&on_disk, &mut path, &mut |s, p| {
        assert!(
            is_allowed_string(s),
            "leak-guard: string at {p} is not on the allowlist: {s:?}"
        );
    });
}

fn walk_strings(value: &Value, path: &mut String, visit: &mut impl FnMut(&str, &str)) {
    match value {
        Value::String(s) => visit(s, path),
        Value::Array(arr) => {
            for (i, v) in arr.iter().enumerate() {
                let saved = path.len();
                use std::fmt::Write;
                let _ = write!(path, "[{i}]");
                walk_strings(v, path, visit);
                path.truncate(saved);
            }
        }
        Value::Object(obj) => {
            for (k, v) in obj {
                let saved = path.len();
                use std::fmt::Write;
                let _ = write!(path, ".{k}");
                walk_strings(v, path, visit);
                path.truncate(saved);
            }
        }
        _ => {}
    }
}

fn is_allowed_string(s: &str) -> bool {
    if s.is_empty() {
        return true;
    }

    // Known-good literals.
    const EXACT: &[&str] = &[
        // Item names (must match the builder exactly)
        "Lonely Login",
        "Exact Duplicate",
        "URI Divergent",
        "Mobile App",
        "Match Mode Divergent",
        "Triple Copy",
        "Two Accounts Same Site",
        "With TOTP",
        "Reprompt Protected",
        "No Password Set",
        "Already Tagged [duplicate]",
        "Trashed Item",
        "Example Payment Card",
        "Example Identity",
        "Example Secure Note",
        // Folder name
        "Folder 01",
        // Literal placeholder for non-string-sensitive fields
        "REDACTED",
    ];
    if EXACT.contains(&s) {
        return true;
    }

    // Family patterns (prefix + structure checks, no regex dep).
    if is_example_user(s)
        || is_redacted_password(s)
        || is_redacted_totp(s)
        || is_example_url(s)
        || is_example_androidapp(s)
        || is_synthetic_uuid(s)
        || is_iso_date(s)
    {
        return true;
    }
    false
}

/// Exact paths the curated fixture's URI builder is allowed to emit.
/// Anything else (including new synthetic paths a future builder might
/// add) must be added here explicitly so the leak-guard doesn't silently
/// start accepting them.
const FIXTURE_URI_PATHS: &[&str] = &["primary", "secondary"];

fn is_example_user(s: &str) -> bool {
    // Exact shape: user<digits>@example.test
    s.strip_prefix("user")
        .and_then(|rest| rest.strip_suffix("@example.test"))
        .is_some_and(|digits| !digits.is_empty() && digits.chars().all(|c| c.is_ascii_digit()))
}

fn is_redacted_password(s: &str) -> bool {
    // Exact shape: redacted-password-<digits> or redacted-password-<digits><single lowercase letter>
    // No other characters are permitted — in particular, "redacted-password-github" is rejected.
    let Some(rest) = s.strip_prefix("redacted-password-") else {
        return false;
    };
    let chars: Vec<char> = rest.chars().collect();
    if chars.is_empty() || !chars[0].is_ascii_digit() {
        return false;
    }
    let mut saw_letter = false;
    for &c in &chars {
        if c.is_ascii_digit() {
            if saw_letter {
                return false; // no digits after a trailing letter
            }
        } else if c.is_ascii_lowercase() {
            if saw_letter {
                return false; // at most one trailing letter
            }
            saw_letter = true;
        } else {
            return false;
        }
    }
    true
}

fn is_redacted_totp(s: &str) -> bool {
    // Exact shape: redacted-totp-seed-<digits>
    s.strip_prefix("redacted-totp-seed-")
        .is_some_and(|rest| !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit()))
}

fn is_example_url(s: &str) -> bool {
    // Exact shape: https://service<digits>.example.test
    //          or: http://service<digits>.example.test
    //          or: <either scheme>://service<digits>.example.test/<FIXTURE_URI_PATHS entry>
    let rest = if let Some(r) = s.strip_prefix("https://") {
        r
    } else if let Some(r) = s.strip_prefix("http://") {
        r
    } else {
        return false;
    };
    let Some(rest) = rest.strip_prefix("service") else {
        return false;
    };
    let Some((num, tail)) = rest.split_once('.') else {
        return false;
    };
    if num.is_empty() || !num.chars().all(|c| c.is_ascii_digit()) {
        return false;
    }
    if tail == "example.test" {
        return true;
    }
    if let Some(path) = tail.strip_prefix("example.test/") {
        return FIXTURE_URI_PATHS.contains(&path);
    }
    false
}

fn is_example_androidapp(s: &str) -> bool {
    // Exact shape: androidapp://com.example.service<digits>
    // In particular, "androidapp://com.example.github" is rejected.
    s.strip_prefix("androidapp://com.example.service")
        .is_some_and(|rest| !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit()))
}

fn is_synthetic_uuid(s: &str) -> bool {
    // All committed UUIDs are zeroed out except the last segment.
    s.len() == 36
        && s.starts_with("00000000-0000-0000-")
        && s.chars().filter(|&c| c == '-').count() == 4
        && s.chars().all(|c| c == '-' || c.is_ascii_hexdigit())
}

fn is_iso_date(s: &str) -> bool {
    // YYYY-MM-DDTHH:MM:SSZ — 20 chars, fixed shape.
    s.len() == 20
        && s.as_bytes().get(4) == Some(&b'-')
        && s.as_bytes().get(7) == Some(&b'-')
        && s.as_bytes().get(10) == Some(&b'T')
        && s.as_bytes().get(13) == Some(&b':')
        && s.as_bytes().get(16) == Some(&b':')
        && s.ends_with('Z')
        && s.chars()
            .enumerate()
            .all(|(i, c)| matches!(i, 4 | 7 | 10 | 13 | 16 | 19) || c.is_ascii_digit())
}

#[test]
fn examples_directory_contains_only_fixture() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("examples");
    let mut entries: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("reading examples/: {e}"))
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .filter(|n| !n.starts_with('.'))
        .collect();
    entries.sort();
    assert_eq!(
        entries,
        vec![FIXTURE_FILENAME.to_string()],
        "examples/ must contain only {FIXTURE_FILENAME} — \
         never commit redactor output, reviewer samples, or scratch files here"
    );
}

#[cfg(test)]
mod allowlist_unit_tests {
    use super::*;

    #[test]
    fn allowlist_accepts_synthetic_examples() {
        assert!(is_allowed_string("user03@example.test"));
        assert!(is_allowed_string("redacted-password-07"));
        assert!(is_allowed_string("redacted-password-07a"));
        assert!(is_allowed_string("redacted-totp-seed-08"));
        assert!(is_allowed_string("https://service01.example.test"));
        assert!(is_allowed_string("https://service03.example.test/primary"));
        assert!(is_allowed_string(
            "https://service03.example.test/secondary"
        ));
        assert!(is_allowed_string("http://service01.example.test"));
        assert!(is_allowed_string("androidapp://com.example.service04"));
        assert!(is_allowed_string("00000000-0000-0000-0000-000000000017"));
        assert!(is_allowed_string("2026-06-01T00:00:00Z"));
        assert!(is_allowed_string("Folder 01"));
        assert!(is_allowed_string("REDACTED"));
    }

    #[test]
    fn allowlist_rejects_real_looking_strings() {
        // Every string in this test is a synthetic placeholder — nothing
        // in the negative test set comes from a real vault. The email
        // uses the RFC 2606 reserved `.example` TLD (guaranteed
        // non-existent); the password is the XKCD 936 stock example;
        // github.com and its Android package are publicly-known strings
        // unrelated to any private user data.
        assert!(!is_allowed_string("real.user@corp.example"));
        assert!(!is_allowed_string("https://github.com"));
        assert!(!is_allowed_string("correct-horse-battery-staple"));
        assert!(!is_allowed_string("androidapp://com.github.android"));
        assert!(!is_allowed_string("2026-03-15T09:45:23.123Z")); // has microseconds
    }

    // --- Shape-specific regressions — these catch the exact failure modes
    //     a loose prefix-matching allowlist would have allowed through. ---

    #[test]
    fn allowlist_rejects_github_in_url_path() {
        // Tight shape should reject any path that isn't in FIXTURE_URI_PATHS.
        assert!(!is_allowed_string("https://service01.example.test/github"));
        assert!(!is_allowed_string("http://service01.example.test/github"));
    }

    #[test]
    fn allowlist_rejects_github_as_android_package() {
        // Only androidapp://com.example.service<digits> is allowed, so
        // anything resembling a real package name is rejected.
        assert!(!is_allowed_string("androidapp://com.example.github"));
        assert!(!is_allowed_string(
            "androidapp://com.example.service_github"
        ));
    }

    #[test]
    fn allowlist_rejects_github_in_password_suffix() {
        // Must start with a digit; pure letters are rejected.
        assert!(!is_allowed_string("redacted-password-github"));
        // Digits followed by multiple letters are rejected.
        assert!(!is_allowed_string("redacted-password-01ab"));
        // Letters followed by digits are rejected.
        assert!(!is_allowed_string("redacted-password-a01"));
    }

    #[test]
    fn allowlist_rejects_custom_uri_paths() {
        // Future builders that want to emit a new path form must update
        // FIXTURE_URI_PATHS, not rely on the allowlist silently accepting it.
        assert!(!is_allowed_string("https://service01.example.test/login"));
        assert!(!is_allowed_string("https://service01.example.test/1"));
    }

    #[test]
    fn allowlist_rejects_real_looking_hostnames_under_example_test() {
        // A real domain smuggled under the synthetic suffix should fail
        // because the host must start with "service<digits>".
        assert!(!is_allowed_string("https://github.example.test"));
        assert!(!is_allowed_string("https://acme.example.test"));
    }
}
